// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type Category struct {
	ID     int32   `json:"id"`
	Desc   *string `json:"desc"`
	Status *int    `json:"status"`
}

type Event struct {
	ID          int32   `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	BannerImage string  `json:"banner_image"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Venue       int     `json:"venue"`
	Type        int     `json:"type"`
	UserID      int32   `json:"user_id"`
	Category    int     `json:"category"`
	Subcategory int     `json:"subcategory"`
	Status      *string `json:"status"`
	Image1      *string `json:"image1"`
	Image2      *string `json:"image2"`
	Image3      *string `json:"image3"`
	Video1      *string `json:"video1"`
	Video2      *string `json:"video2"`
}

type EventType struct {
	ID     int32   `json:"id"`
	Desc   *string `json:"desc"`
	Status *int    `json:"status"`
}

type GetEvent struct {
	Category    int     `json:"category"`
	Subcategory int     `json:"subcategory"`
	City        *string `json:"city"`
	Province    *string `json:"province"`
	PageSize    int     `json:"pageSize"`
	Offset      int     `json:"offset"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token   *string `json:"token"`
	User    *User   `json:"user"`
	Success bool    `json:"success"`
	Message *string `json:"message"`
}

type NewEvent struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	BannerImage string  `json:"banner_image"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Venue       int     `json:"venue"`
	Type        int     `json:"type"`
	UserID      int32   `json:"user_id"`
	Category    int     `json:"category"`
	Subcategory int     `json:"subcategory"`
	Status      *string `json:"status"`
	Image1      *string `json:"image1"`
	Image2      *string `json:"image2"`
	Image3      *string `json:"image3"`
	Video1      *string `json:"video1"`
	Video2      *string `json:"video2"`
}

type NewUser struct {
	Title     string `json:"title"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Usertype  int    `json:"usertype"`
}

type NewVenue struct {
	Name        string `json:"name"`
	Address     string `json:"address"`
	City        string `json:"city"`
	Province    string `json:"province"`
	CountryCode string `json:"country_code"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Subcategory struct {
	ID     int32   `json:"id"`
	Desc   *string `json:"desc"`
	Status *int    `json:"status"`
}

type User struct {
	ID        int32  `json:"id"`
	Title     string `json:"title"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Usertype  int    `json:"usertype"`
}

type Usertype struct {
	ID     int32   `json:"id"`
	Desc   *string `json:"desc"`
	Status *int    `json:"status"`
}

type Venue struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Address     string `json:"address"`
	City        string `json:"city"`
	Province    string `json:"province"`
	CountryCode string `json:"country_code"`
}
