// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type Category struct {
	ID     int32  `json:"id"`
	Desc   string `json:"desc"`
	Image  string `json:"image"`
	Status int    `json:"status"`
}

type Event struct {
	ID          int32      `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	BannerImage string     `json:"banner_image"`
	StartDate   string     `json:"startDate"`
	EndDate     string     `json:"endDate"`
	Venue       int        `json:"venue"`
	Type        int        `json:"type"`
	UserID      int32      `json:"user_id"`
	Category    int        `json:"category"`
	Subcategory int        `json:"subcategory"`
	Sponsors    []*Sponsor `json:"sponsors"`
	HostID      int        `json:"hostID"`
	Ticket      []*Ticket  `json:"ticket"`
	Status      int        `json:"status"`
	Images      []*Image   `json:"images"`
	Videos      []*Video   `json:"videos"`
}

type EventType struct {
	ID     int32  `json:"id"`
	Desc   string `json:"desc"`
	Status int    `json:"status"`
}

type GetEvent struct {
	Category    int `json:"category"`
	Subcategory int `json:"subcategory"`
	PageSize    int `json:"pageSize"`
	Offset      int `json:"offset"`
	Status      int `json:"status"`
}

type GetEventByLocation struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Miles     int     `json:"miles"`
}

type Host struct {
	ID     int32    `json:"id"`
	UserID int      `json:"user_id"`
	Events []*Event `json:"events"`
}

type Image struct {
	ID      int32   `json:"id"`
	EventID int32   `json:"event_id"`
	Name    string  `json:"name"`
	URL     *string `json:"url"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token   *string `json:"token"`
	User    *User   `json:"user"`
	Success bool    `json:"success"`
	Message *string `json:"message"`
}

type NewEvent struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	BannerImage string      `json:"banner_image"`
	StartDate   string      `json:"startDate"`
	EndDate     string      `json:"endDate"`
	Venue       int         `json:"venue"`
	Type        int         `json:"type"`
	UserID      int32       `json:"user_id"`
	Category    int         `json:"category"`
	Subcategory int         `json:"subcategory"`
	Status      int         `json:"status"`
	Images      []*NewImage `json:"images"`
	Vidoes      []*NewVideo `json:"vidoes"`
}

type NewHost struct {
	UserID  int `json:"user_id"`
	EventID int `json:"event_id"`
}

type NewImage struct {
	Name string  `json:"name"`
	URL  *string `json:"url"`
}

type NewSponsor struct {
	UserID  int `json:"user_id"`
	EventID int `json:"event_id"`
}

type NewTicket struct {
	Name     string `json:"name"`
	Price    int    `json:"price"`
	EventID  int    `json:"event_id"`
	Quantity int    `json:"quantity"`
	Status   int    `json:"status"`
	Currency string `json:"currency"`
}

type NewUser struct {
	Phone     *string `json:"phone"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	Usertype  int     `json:"usertype"`
	Avatar    *string `json:"avatar"`
}

type NewVenue struct {
	Name        string   `json:"name"`
	Address     *string  `json:"address"`
	PostalCode  *string  `json:"postal_code"`
	City        *string  `json:"city"`
	Province    *string  `json:"province"`
	CountryCode *string  `json:"country_code"`
	URL         *string  `json:"url"`
	Virtual     bool     `json:"virtual"`
	Longitude   *float64 `json:"longitude"`
	Latitude    *float64 `json:"latitude"`
}

type NewVideo struct {
	Name string  `json:"name"`
	URL  *string `json:"url"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Sponsor struct {
	ID     int32    `json:"id"`
	UserID int      `json:"user_id"`
	Events []*Event `json:"events"`
}

type Subcategory struct {
	ID     int32  `json:"id"`
	Desc   string `json:"desc"`
	Status int    `json:"status"`
}

type Ticket struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Price    int    `json:"price"`
	EventID  int    `json:"event_id"`
	Quantity int    `json:"quantity"`
	Status   int    `json:"status"`
	Currency string `json:"currency"`
}

type UpdateEvent struct {
	ID          int         `json:"id"`
	Title       *string     `json:"title"`
	Description *string     `json:"description"`
	BannerImage *string     `json:"banner_image"`
	StartDate   *string     `json:"startDate"`
	EndDate     *string     `json:"endDate"`
	Venue       *int        `json:"venue"`
	Type        *int        `json:"type"`
	Category    *int        `json:"category"`
	Status      *int        `json:"status"`
	Images      []*NewImage `json:"images"`
	Vidoes      []*NewVideo `json:"vidoes"`
}

type UpdateEventState struct {
	EventID     int `json:"event_id"`
	EventStatus int `json:"event_status"`
}

type UpdateEventStatus struct {
	EventID     int `json:"event_id"`
	EventStatus int `json:"event_status"`
}

type User struct {
	ID        int32   `json:"id"`
	Phone     *string `json:"phone"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	Usertype  int     `json:"usertype"`
	Avatar    string  `json:"avatar"`
}

type Usertype struct {
	ID     int32  `json:"id"`
	Desc   string `json:"desc"`
	Status *int   `json:"status"`
}

type Venue struct {
	ID          int32    `json:"id"`
	Name        string   `json:"name"`
	Address     *string  `json:"address"`
	PostalCode  *string  `json:"postal_code"`
	City        *string  `json:"city"`
	Province    *string  `json:"province"`
	CountryCode *string  `json:"country_code"`
	Longitude   *float64 `json:"Longitude"`
	Latitude    *float64 `json:"Latitude"`
	URL         *string  `json:"url"`
	Virtual     bool     `json:"virtual"`
	Rating      float64  `json:"rating"`
}

type Video struct {
	ID      int32   `json:"id"`
	EventID int32   `json:"event_id"`
	Name    string  `json:"name"`
	URL     *string `json:"url"`
}
