version: "3.9"
services:
  database:
    image: postgres:12-alpine
    restart: always
    env_file:
      - app.env
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: app.env
    depends_on:
      - database
    ports:
      - "8080:8080"


