// Code generated by sqlc. DO NOT EDIT.
// source: hosts.sql

package db

import (
	"context"
)

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (
user_id
) VALUES
    ($1) RETURNING id, user_id, display_name, avatar_url, short_bio, created_at
`

func (q *Queries) CreateHost(ctx context.Context, userID int32) (Host, error) {
	row := q.db.QueryRowContext(ctx, createHost, userID)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ShortBio,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHost = `-- name: DeleteHost :exec
DELETE from hosts
WHERE id = $1
`

func (q *Queries) DeleteHost(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteHost, id)
	return err
}

const getHost = `-- name: GetHost :one
SELECT id, user_id, display_name, avatar_url, short_bio, created_at from hosts
WHERE id = $1
`

func (q *Queries) GetHost(ctx context.Context, id int32) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ShortBio,
		&i.CreatedAt,
	)
	return i, err
}

const getHostByEvent = `-- name: GetHostByEvent :many
SELECT id, event_id, host_id, created_at from events_hosts
WHERE event_id = $1
`

func (q *Queries) GetHostByEvent(ctx context.Context, eventID int32) ([]EventsHost, error) {
	rows, err := q.db.QueryContext(ctx, getHostByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsHost{}
	for rows.Next() {
		var i EventsHost
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.HostID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkHostToEvent = `-- name: LinkHostToEvent :one
INSERT INTO events_hosts(
host_id,event_id)
VALUES($1, $2 ) RETURNING id, event_id, host_id, created_at
`

type LinkHostToEventParams struct {
	HostID  int32 `json:"host_id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) LinkHostToEvent(ctx context.Context, arg LinkHostToEventParams) (EventsHost, error) {
	row := q.db.QueryRowContext(ctx, linkHostToEvent, arg.HostID, arg.EventID)
	var i EventsHost
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.HostID,
		&i.CreatedAt,
	)
	return i, err
}

const updateEventHost = `-- name: UpdateEventHost :exec
UPDATE events_hosts
set event_id= $1
WHERE id=$2
`

type UpdateEventHostParams struct {
	EventID int32 `json:"event_id"`
	ID      int32 `json:"id"`
}

func (q *Queries) UpdateEventHost(ctx context.Context, arg UpdateEventHostParams) error {
	_, err := q.db.ExecContext(ctx, updateEventHost, arg.EventID, arg.ID)
	return err
}

const updateHost = `-- name: UpdateHost :one
UPDATE hosts SET
 display_name = CASE WHEN $1::boolean
        THEN $2::text ELSE display_name END, 
 avatar_url = CASE WHEN $3::boolean
        THEN $4::text ELSE avatar_url END,
 short_bio = CASE WHEN $5::boolean
        THEN $6::text ELSE short_bio END
WHERE id = $7 RETURNING id, user_id, display_name, avatar_url, short_bio, created_at
`

type UpdateHostParams struct {
	DisplayNameToUpdate bool   `json:"display_name_to_update"`
	DisplayName         string `json:"display_name"`
	AvatarUrlToUpdate   bool   `json:"avatar_url_to_update"`
	AvatarUrl           string `json:"avatar_url"`
	ShortBioToUpdate    bool   `json:"short_bio_to_update"`
	ShortBio            string `json:"short_bio"`
	ID                  int32  `json:"id"`
}

func (q *Queries) UpdateHost(ctx context.Context, arg UpdateHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, updateHost,
		arg.DisplayNameToUpdate,
		arg.DisplayName,
		arg.AvatarUrlToUpdate,
		arg.AvatarUrl,
		arg.ShortBioToUpdate,
		arg.ShortBio,
		arg.ID,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ShortBio,
		&i.CreatedAt,
	)
	return i, err
}
