// Code generated by sqlc. DO NOT EDIT.
// source: sponsors.sql

package db

import (
	"context"
)

const createSponsor = `-- name: CreateSponsor :one
INSERT INTO sponsors (
user_id
) VALUES
    ($1) RETURNING id, user_id, display_name, avatar_url, short_bio, created_at
`

func (q *Queries) CreateSponsor(ctx context.Context, userID int32) (Sponsor, error) {
	row := q.db.QueryRowContext(ctx, createSponsor, userID)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ShortBio,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSponsor = `-- name: DeleteSponsor :exec
DELETE from sponsors
WHERE id = $1
`

func (q *Queries) DeleteSponsor(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSponsor, id)
	return err
}

const getSponsor = `-- name: GetSponsor :one
SELECT id, user_id, display_name, avatar_url, short_bio, created_at from sponsors
WHERE id = $1
`

func (q *Queries) GetSponsor(ctx context.Context, id int32) (Sponsor, error) {
	row := q.db.QueryRowContext(ctx, getSponsor, id)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ShortBio,
		&i.CreatedAt,
	)
	return i, err
}

const getSponsorByEvent = `-- name: GetSponsorByEvent :many
SELECT id, event_id, sponsor_id, created_at from events_sponsors
WHERE event_id = $1
`

func (q *Queries) GetSponsorByEvent(ctx context.Context, eventID int32) ([]EventsSponsor, error) {
	rows, err := q.db.QueryContext(ctx, getSponsorByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsSponsor{}
	for rows.Next() {
		var i EventsSponsor
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SponsorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSponsorToEvent = `-- name: LinkSponsorToEvent :one
INSERT INTO events_sponsors(
sponsor_id,event_id) 
VALUES($1, $2 ) RETURNING id, event_id, sponsor_id, created_at
`

type LinkSponsorToEventParams struct {
	SponsorID int32 `json:"sponsor_id"`
	EventID   int32 `json:"event_id"`
}

func (q *Queries) LinkSponsorToEvent(ctx context.Context, arg LinkSponsorToEventParams) (EventsSponsor, error) {
	row := q.db.QueryRowContext(ctx, linkSponsorToEvent, arg.SponsorID, arg.EventID)
	var i EventsSponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SponsorID,
		&i.CreatedAt,
	)
	return i, err
}

const updateSponsor = `-- name: UpdateSponsor :one
UPDATE sponsors SET
 display_name = CASE WHEN $1::boolean
        THEN $2::text ELSE display_name END, 
 avatar_url = CASE WHEN $3::boolean
        THEN $4::text ELSE avatar_url END,
 short_bio = CASE WHEN $5::boolean
        THEN $6::text ELSE short_bio END
WHERE id = $7 RETURNING id, user_id, display_name, avatar_url, short_bio, created_at
`

type UpdateSponsorParams struct {
	DisplayNameToUpdate bool   `json:"display_name_to_update"`
	DisplayName         string `json:"display_name"`
	AvatarUrlToUpdate   bool   `json:"avatar_url_to_update"`
	AvatarUrl           string `json:"avatar_url"`
	ShortBioToUpdate    bool   `json:"short_bio_to_update"`
	ShortBio            string `json:"short_bio"`
	ID                  int32  `json:"id"`
}

func (q *Queries) UpdateSponsor(ctx context.Context, arg UpdateSponsorParams) (Sponsor, error) {
	row := q.db.QueryRowContext(ctx, updateSponsor,
		arg.DisplayNameToUpdate,
		arg.DisplayName,
		arg.AvatarUrlToUpdate,
		arg.AvatarUrl,
		arg.ShortBioToUpdate,
		arg.ShortBio,
		arg.ID,
	)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ShortBio,
		&i.CreatedAt,
	)
	return i, err
}
